# Site settings
title: My New Adventure
header-img: img/home-bg.png
email: vmcclimon33@yahoo.com
copyright_name: LynieV
description: > # this means to ignore newlines until "baseurl:"
  Hello Life
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  LynieV
learn_profile: LynieV
email_username: vmcclimon33@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
